### ISSUE TITLE
Suggestion: handle specific cases, otherwise fallback to inferred type

### ISSUE THREAD

**Issue by kootenpv** [sminez/concepts#1]
Hi, great idea!

I was thinking perhaps for some types other than special like str, bytes (too bad they don't work) and dict, you could do this:

```
some = [1, 2, 3]
the_type = type(some)
the_type(fn(x) for x in some)
```

In fact, that works for tuples and lists (actually does **not** work for generators). It _will_  work nicely for custom types that are no isinstance of the faulty ones.

So yea, the main point is that if I make a SuperList that just behaves exactly like a list, you should test for whether it requires special needs, and otherwise use `the_type(fn(x) for x in some)` to return the original type, such as SuperList.

**Comment by sminez** [comment]
Thanks for the suggestion! Could you explain what do you mean about bytes not working and 'faulty ones'? (fmapping over bytes works for me).

Is your idea to completely replace the default implementation (`_fmap`) with this? As you've shown it, this has some unexpected behaviour. Defaultdicts for example: as implemented currently fmap will return a normal dict unless the programmer (or me I suppose if I add a case!) specify how to handle them.

`defaultdict(fn(x) for x in col)` however results in a type error as the first argument to the defaultdict constructor is the factory function to produce the default value.

I think in general, I'd prefer the case where a type has a missing definition to return a known value (either a generator or a list) rather than produce an exception because trying to use an inferred constructor didn't work.

Any ideas of how to work around that?

**Comment by kootenpv** [comment]
What I meant with "bytes not working" was that my suggested idea by using the inferred type does not work on bytes. I'm aware that is being handled just fine in fmap.

I guess you're right, it starts to look like there are more exceptions than rules. 
Maybe we can do a bit better though:

In case of either built-in types or inheriting from those:
- Test with `isinstance`, and implement a solution for each group (bytes, dict, list).
- However, instantiate with the original type (which might be SuperList or just a list)

When the iterator is not a known instance group:
- Use the original type
- If this crashes, inform user to change to e.g. `default=list` (when default=None, it tries its own type). E.g.:

``` python
raise TypeError("Cannot instantiate in a safe way, to continue anyway, use default=list")
```

Sounds reasonable?

Another idea is to just use either list/generator as default, and allow user to `default=MyOwnClass`. Though I think this might be more confusing / lead to more confusing code.

Perhaps you could just make it into 2 functions to explicitly communicate this difference.

**Comment by sminez** [comment]
Hmm...I I think I see what you're aiming at but I'm not sure I agree with your approach.

Conceptually, fmap is a very simple operation and all of the type based dispatch is handled by the `singledispatch` decorator from functools. I think that having additional additional checking and branches within `_fmap` itself feels counter productive to this.

My idea was to provide defaults for built in types and have the `fmap_for` decorator (and `instance` function) to allow programmers to quickly add their implementation for their own classes / types. If writing the definition for `fmap` for your class is too complicated then most likely your class is too complicated as a data-structure!

For example, if we have a (very) simple recursive binary tree class:

```
# NOTE: Here, left and right are either None or another binary tree.
# You would probably want to enforce this but this is just for demo purposes ;)

class Btree:
    def __init__(self, val, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

    def __repr__(self):
        return str((self.val, self.left, self.right))
```

Then we just add one extra function definition to make fmap work with it:

```
@fmap_for(Btree)
def _fmap_btree(t, func):
    return Btree(func(t.val), fmap(func, t.left), fmap(func, t.right))


>>> b = Btree(4, Btree(3, Btree(2)), Btree(1, None, Btree(0)))
>>> b
(4, (3, (2, None, None), None), (1, None, (0, None, None)))
>>> b.left
(3, (2, None, None), None)
>>> b.right
(1, None, (0, None, None))

>>> fmap(times2, b)
(8, (6, (4, None, None), None), (2, None, (0, None, None)))
```

All of the examples in the README are iterator based because the standard datatypes implement the iterator protocol. You are free to define fmap on your class to work however suits your use case: here, if we reduce the binary tree to a stream of values coming from an iterator then we lose all of the structure that makes the tree itself useful.

As the writer of the class, I know that it is recursively defined and that a recursive definition for fmap is going to work well with how I use it (usual caveats around recursion in Python being accounted for).

_This_ is the aim behind `fmap`, sensible defaults for the programmer and an easy way to add their own implementation. Thinking about it though (and chatting to a colleague at work this morning) it probably makes more sense to have the default implementation raise a `TypeError` no matter what along with a short signposting to the docs on `fmap_for`. That way, built in types work as expected and you don't need to worry about `fmap` trying to be clever behind your back.

Do you think that's an acceptable resolution to the problem?

**Comment by kootenpv** [comment]
I guess my "research" was too shallow, your approach seems very sensible of allowing users to easily implement fmap on their data structure. Also the final paragraph seems very user friendly. 

In my opinion the case can be closed :)

**Comment by sminez** [comment]
Fab! Thank you for raising the issue: it made me think about what I was doing correctly :)
